name: tgs
description: Telegram Animated Sticker widget for flutter support cross platform.
 
version: 0.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2 
  archive: ^3.3.6
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
 
flutter: 
  uses-material-design: true